<?php

/**
 * @file
 * Page Json module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function page_json_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $form['site_information']['site_api_key'] = [
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#default_value' => \Drupal::state()->get('siteapikey', 'No API Key yet'),
      '#description' => t("Site API key to be used for validation"),
    ];
    $form['actions']['submit']['#submit'][] = 'siteapikey_submit';
    $form['actions']['submit']['#value'] = t('Update Configuration');
  }
}

/**
 * Submit handler for page_json_form_alter().
 */
function siteapikey_submit($form, FormStateInterface $form_state) {
  \Drupal::state()->set('siteapikey', $form_state->getValue('site_api_key'));
  drupal_set_message(t('Site API value is set succesfullly'), 'status');
}
